---
name: "clear"
version: "0.2.2"
usage: "Please see https://github.com/mocyuto/helm-clear"
description: "clear helm resources which are older revisions"
command: "$HELM_PLUGIN_DIR/bin/clear"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install-binary.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install-binary.sh"
